# 範例
***

# [教學目標]

* 正確的使用 NumPy 中的算術運算
* 了解 NumPy 陣列與數學矩陣的關係
* 知道 NumPy 與 SciPy 差異為何


In [1]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/__init__.py'>
1.20.1


In [12]:
# 相同大小的陣列運算

import numpy as np

a = np.array( [20,30,40,50] )
b = np.arange( 4)

print(a + b)
print(a * b)

In [13]:
kk =np.array([40,60,80,100])
bb = np.array([1,2])
kk+bb

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [3]:
# 常數與陣列運算

import numpy as np

a = np.array( [20,30,40,50] )

print(a - 2)
print(a / 10)


[18 28 38 48]
[2. 3. 4. 5.]


In [3]:
# 不同大小的陣列運算

import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])#4,2
ones_row = np.array([[1, 1]])#1,1

print(data + ones_row)


[[2 3]
 [4 5]
 [6 7]]


In [4]:
# 陣列運算與容器運算的差異

a = np.array( [20,30,40,50] )
print(a + 1)

a = [20, 30, 40, 50]
b = []
for i in a:
    b.append(i+1)
print(b)


[21 31 41 51]
[21, 31, 41, 51]


In [5]:
# 用於陣列的矩陣運算

a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)
y = np.array([[5.], [7.]])
print(y)

[[1. 2.]
 [3. 4.]]
[[5.]
 [7.]]


In [10]:
print(a.transpose())#矩陣轉置 == a.T 
print(np.linalg.inv(a))#linalg.inv 逆矩陣 >> AB=BA=E >>B是A的逆矩阵 >> A則被稱為可逆矩阵
print(np.trace(a))#計算對角線元素的和
print(np.linalg.solve(a, y))#ax=y x==[[-3][4]] 以矩陣的方式解線性方程式


[[1. 3.]
 [2. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
5.0
[[-3.]
 [ 4.]]
