# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [3]:
import numpy as np


In [8]:
'''
Your Code
'''
a = np.random.randint(10, size=6) 
print('list(a): ', list(a))#只轉第一層
print('tolist(): ', a.tolist())#全部轉成陣列

array([3, 7, 2, 6, 3, 8])

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [9]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

In [13]:

a = np.random.randint(10, size=6) 

'''
Your Code
'''
print(a)
print(a.ndim)#陣列維度
print(a.shape)#陣列的形狀
print(a.size)#陣列中共有幾個元素
print(a.dtype)#陣列的型態
print(a.itemsize)#陣列中元素的大小
print(type(a))#確認型態

[9 6 3 3 1 2]
1
(6,)
6
int64
8


In [14]:
b = np.random.randint(10, size=(3,4)) 

'''
Your Code
'''
print(b)
print(b.ndim)#陣列維度
print(b.shape)#陣列的形狀
print(b.size)#陣列中共有幾個元素
print(b.dtype)#陣列的型態
print(b.itemsize)#陣列中元素的大小
print(type(b))#確認型態

[[5 6 0 5]
 [6 3 5 9]
 [8 8 2 9]]
2
(3, 4)
12
int64
8


In [16]:
c = np.random.randint(10, size=(2,3,2)) 

'''
Your Code
'''
print(c)
print(c.ndim)#陣列維度
print(c.shape)#陣列的形狀
print(c.size)#陣列中共有幾個元素
print(c.dtype)#陣列的型態
print(c.itemsize)#陣列中元素的大小
print(type(c))#確認型態

[[[1 7]
  [4 7]
  [1 9]]

 [[9 9]
  [4 4]
  [6 5]]]
3
(2, 3, 2)
12
int64
8
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [17]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[3, 9, 0, 5, 9, 0]
[3, 9, 0, 5, 9, 0]


In [18]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[8, 3, 2, 4], [0, 5, 7, 0], [4, 1, 9, 2]]
[array([8, 3, 2, 4]), array([0, 5, 7, 0]), array([4, 1, 9, 2])]


In [19]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[1, 4], [7, 9], [7, 9]], [[5, 2], [7, 5], [3, 9]]]
[array([[1, 4],
       [7, 9],
       [7, 9]]), array([[5, 2],
       [7, 5],
       [3, 9]])]


In [24]:
def tolist(iterable):
    '''
    Your Code
    '''
    a=[i.tolist() for i in iterable ]
    return a
    
        

print(tolist(a))
print(tolist(b))
print(tolist(c))

[3, 9, 0, 5, 9, 0]
[[8, 3, 2, 4], [0, 5, 7, 0], [4, 1, 9, 2]]
[[[1, 4], [7, 9], [7, 9]], [[5, 2], [7, 5], [3, 9]]]


[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
