# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


'''
Your Code
'''
np.empty >> 1.所產生出來的數組是無意義的數值，主要是返回一個空的數組，2.用於填入同形狀的數組


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [1]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

In [37]:
# 參考解答

a = np.random.rand(2, 3)

print(a)
'''
Your Code
'''

a.round()

[[2.08337817e-01 1.44152930e-01 4.28678275e-01]
 [3.58325715e-04 7.00504117e-01 6.09362494e-02]]


array([[0., 0., 0.],
       [0., 1., 0.]])

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [39]:
m = 20
n = 40

'''
Your Code
'''
np.random.randint(20,40,size=(2,3))

array([[36, 34, 23],
       [31, 32, 34]])