# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:
'''
Your Code
'''
print(a.sum()) #陣列屬性的方式
print(np.sum(a))#方法的方式
print(sum(a))#用python原有的方法

'\nYour Code\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [1]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

In [3]:
A = np.random.random((5, 5))
print(A)


'''
Your Code
'''

[[0.98050752 0.82355402 0.47493504 0.25993718 0.70751648]
 [0.22966828 0.03278006 0.00761995 0.05110385 0.48962621]
 [0.15620572 0.6817124  0.91563362 0.37781579 0.10794362]
 [0.08503489 0.20278123 0.80547061 0.79999562 0.09687104]
 [0.07891044 0.17013626 0.85355125 0.68269592 0.18299906]]


'\nYour Code\n'

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [32]:
'''
Your Code
'''

a=np.random.rand((10))
a.sort()
a[9]=-1
print(a)

[ 0.00901693  0.0676844   0.1307692   0.25111499  0.44335532  0.61932281
  0.70818677  0.84341312  0.92906604 -1.        ]


array([ 0.02063326,  0.0397939 ,  0.11659267,  0.2563304 ,  0.34367928,
        0.40211629,  0.42706811,  0.62579032,  0.76625514, -1.        ])