# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [1]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

In [13]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
Z

array([[[9, 8, 7, ..., 6, 0, 6],
        [9, 0, 1, ..., 3, 2, 4],
        [1, 3, 1, ..., 6, 5, 3],
        ...,
        [1, 7, 5, ..., 2, 5, 3],
        [3, 2, 3, ..., 2, 6, 3],
        [1, 6, 4, ..., 1, 2, 5]],

       [[4, 7, 6, ..., 8, 4, 5],
        [4, 7, 0, ..., 4, 0, 4],
        [1, 2, 3, ..., 3, 9, 9],
        ...,
        [0, 2, 5, ..., 5, 1, 1],
        [4, 6, 5, ..., 7, 9, 0],
        [5, 4, 8, ..., 7, 7, 4]],

       [[6, 9, 4, ..., 5, 9, 4],
        [7, 3, 4, ..., 4, 3, 8],
        [1, 2, 9, ..., 4, 2, 1],
        ...,
        [0, 7, 2, ..., 4, 1, 3],
        [9, 2, 4, ..., 5, 8, 5],
        [5, 4, 3, ..., 0, 7, 2]],

       ...,

       [[0, 7, 3, ..., 1, 2, 5],
        [0, 1, 0, ..., 1, 9, 6],
        [8, 0, 4, ..., 4, 4, 3],
        ...,
        [8, 5, 4, ..., 6, 0, 5],
        [7, 2, 2, ..., 8, 3, 7],
        [4, 7, 8, ..., 6, 9, 6]],

       [[0, 7, 5, ..., 1, 7, 2],
        [5, 1, 7, ..., 9, 5, 6],
        [0, 3, 3, ..., 5, 5, 8],
        ...,
        [2, 4, 2, ..., 

In [14]:
%timeit -n 10 a = 2

'''
Your Code
'''
Z+1

39.2 ns ± 20.9 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[10,  9,  8, ...,  7,  1,  7],
        [10,  1,  2, ...,  4,  3,  5],
        [ 2,  4,  2, ...,  7,  6,  4],
        ...,
        [ 2,  8,  6, ...,  3,  6,  4],
        [ 4,  3,  4, ...,  3,  7,  4],
        [ 2,  7,  5, ...,  2,  3,  6]],

       [[ 5,  8,  7, ...,  9,  5,  6],
        [ 5,  8,  1, ...,  5,  1,  5],
        [ 2,  3,  4, ...,  4, 10, 10],
        ...,
        [ 1,  3,  6, ...,  6,  2,  2],
        [ 5,  7,  6, ...,  8, 10,  1],
        [ 6,  5,  9, ...,  8,  8,  5]],

       [[ 7, 10,  5, ...,  6, 10,  5],
        [ 8,  4,  5, ...,  5,  4,  9],
        [ 2,  3, 10, ...,  5,  3,  2],
        ...,
        [ 1,  8,  3, ...,  5,  2,  4],
        [10,  3,  5, ...,  6,  9,  6],
        [ 6,  5,  4, ...,  1,  8,  3]],

       ...,

       [[ 1,  8,  4, ...,  2,  3,  6],
        [ 1,  2,  1, ...,  2, 10,  7],
        [ 9,  1,  5, ...,  5,  5,  4],
        ...,
        [ 9,  6,  5, ...,  7,  1,  6],
        [ 8,  3,  3, ...,  9,  4,  8],
        [ 5,  8,  9, ...,  7, 10

In [11]:
%timeit -n 10 a = 2

'''
Your Code
'''

37.2 ns ± 15.6 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


'\nYour Code\n'

In [ ]:
%timeit -n 10 a = 2

'''
Your Code
'''

### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [58]:

Z = np.random.randint(0,10,50)
print(Z)
print(len(Z))


[7 5 0 8 1 1 8 9 9 4 8 9 0 8 4 3 5 4 1 1 7 4 7 6 0 8 2 0 5 4 7 0 3 2 4 5 7
 6 3 3 9 6 6 1 7 1 1 5 6 5]
50


In [60]:
'''
Your Code
'''
a,s = np.unique(Z, return_counts=True)
print(a)
print(s)
num=a[np.argmax(s)]
print(f"出現多次數的數值是:{num},約{np.max(s)}次") 

[0 1 2 3 4 5 6 7 8 9]
[5 7 2 4 6 6 5 6 5 4]
出現多次數的數值是:1,約7次


In [61]:
'''
Your Code
'''
np.where(Z==num)

(array([ 4,  5, 18, 19, 43, 45, 46]),)

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [62]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[7, 4, 6, 9, 5, 3]
[7, 4, 6, 9, 5, 3]
[[7, 5, 1, 9], [9, 3, 8, 2], [4, 0, 4, 7]]
[array([7, 5, 1, 9]), array([9, 3, 8, 2]), array([4, 0, 4, 7])]
[[[2, 9], [6, 0], [6, 1]], [[1, 9], [2, 5], [1, 9]]]
[array([[2, 9],
       [6, 0],
       [6, 1]]), array([[1, 9],
       [2, 5],
       [1, 9]])]


In [87]:
'''
Your Code
'''
a1=[]
for i in a.flat:
    a1.append(i)
b1=[]
for i in b:
    b1.append(list(i))
c1=[]
for i in c:
    a=[]
    for k in i:
        a.append(list(k))
    c1.append(a)
        

In [88]:

c1

[[[2, 9], [6, 0], [6, 1]], [[1, 9], [2, 5], [1, 9]]]